name: System Software review build

on:
  push:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - b0-v*
      - main
      - b1-v*
      - v*
  pull_request:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - main
      - b0-v*
      - b1-v*
      - v*

  workflow_dispatch:

env:
  CMAKE_VERSION: 3.20.5
  WEST_VERSION: 0.14.0
  SDK_VERSION: 0.15.0

jobs:
  zephyr_build:
    name: Build Zephyr before merge
    runs-on: ubuntu-20.04
    steps:
      - name: setup host
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip cmake git

      - name: checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: check spell and Jira ID 
        run : |
          pip install codespell
          codespell --version
          git show | grep "^+" | codespell - || ( \
          echo "ERROR:codespell gave the above suggestion on spelling." \
          && echo "Correct them and submit again" && exit 1)
          temp_file="${RUNNER_TEMP}/git_log.txt"
          git log -1 > $temp_file
          # check for Jira ID in the first line of the commit
          cat $temp_file | head -5 | tail -1 | grep -q "[A-Z]\+-[0-9]\+" || \
          (echo "ERROR:first line of the commit should contain Jira ID." && \
          exit 1)
          # check for Source field
          cat $temp_file | grep -q "Source:" || \
          (echo "ERROR:The commit message should contain 'Source:' field." \
          && exit 1)
          # check for Jira ID field
          cat $temp_file | grep -q "JIRA ID:.*[A-Z]\+-[0-9]\+" || \
          (echo "ERROR:The commit message should contain 'JIRA ID:' field." \
          && exit 1)
          # check for Type field
          cat $temp_file | egrep -q \
          "Type:.*(Defect Fix|Security Fix|Development|Integration|Enhancement)" \
          || (echo "ERROR:The commit message should contain 'Type:' field." \
          && exit 1)
          # check for Disposition field
          cat $temp_file | egrep -q \
          "Disposition:.*(Local|Backport from|Ported from)" || (echo \
          "ERROR:The commit message should contain 'Disposition:' field." \
          && exit 1)
          # check for Description field
          cat $temp_file | egrep -q "Description:" || (echo \
          "ERROR:The commit message should contain 'Description:' field." \
          && exit 1)
     
      - name: install west cmake
        run: |
          sudo pip3 install -U setuptools wheel pip
          pip3 install west==${WEST_VERSION} pyelftools
          pip3 install cmake==${CMAKE_VERSION}
      - name: install toolchain
        run: |
          mkdir -p ${{ runner.temp }}/../toolchain/
          pushd ${{ runner.temp }}/../toolchain/
          wget --no-verbose "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${SDK_VERSION}/zephyr-sdk-${SDK_VERSION}_linux-x86_64_minimal.tar.gz"
          tar -xf zephyr-sdk-${SDK_VERSION}_linux-x86_64_minimal.tar.gz
          wget --no-verbose "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${SDK_VERSION}/toolchain_linux-x86_64_arm-zephyr-eabi.tar.gz"
          tar -xf toolchain_linux-x86_64_arm-zephyr-eabi.tar.gz -C zephyr-sdk-${SDK_VERSION}
          pushd zephyr-sdk-${SDK_VERSION}
          SDK_PATH=$PWD
          ./setup.sh -h -c
          readlink -f "$PWD/arm-zephyr-eabi/bin" >> $GITHUB_PATH
          popd
          popd

      - name: setup west
        run: |
          echo "Workflow being run by ${{ github.actor }} ID: ${{ github.actor_id }}"
          echo "Github SHA commit ID: ${{ github.sha }}"
          west init -l .
          west update
          west config zephyr.base $PWD

      - name: build for primary board
        run: |
          #pushd ..
          #ln -sf zephyr_rv zephyr
          #popd
          source ${{ runner.temp }}/../toolchain/zephyr-sdk-${SDK_VERSION}/environment-setup-x86_64-pokysdk-linux
          west build -b qemu_cortex_m3 samples/hello_world -- -G"Unix Makefiles"
