name: System Software review build

on:
  push:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - b0-v*
      - main
      - b1-v*
      - v*
  pull_request:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - main
      - b0-v*
      - b1-v*
      - v*

  workflow_dispatch:

env:
  CMAKE_VERSION: 3.20.5
  WEST_VERSION: 0.14.0
  SDK_VERSION: 0.15.0

jobs:
  zephyr_build:
    name: Build Zephyr before merge
    runs-on: ubuntu-20.04
    steps:
      - name: setup host
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip cmake git

      - name: checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: check spell and Jira ID 
        run : |
          pip install codespell
          codespell --version
          git show | grep "^+" | codespell - > ${RUNNER_TEMP}/addition_diff ||\
          echo "ERROR:codespell gave the following suggestion on spelling." \
          && echo "Correct them and submit again" \
          && cat ${RUNNER_TEMP}/addition_diff && exit 1

      - name: install west cmake
        run: |
          sudo pip3 install -U setuptools wheel pip
          pip3 install west==${WEST_VERSION} pyelftools
          pip3 install cmake==${CMAKE_VERSION}
      - name: install toolchain
        run: |
          mkdir -p ${{ runner.temp }}/../toolchain/
          pushd ${{ runner.temp }}/../toolchain/
          wget --no-verbose "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${SDK_VERSION}/zephyr-sdk-${SDK_VERSION}_linux-x86_64_minimal.tar.gz"
          tar -xf zephyr-sdk-${SDK_VERSION}_linux-x86_64_minimal.tar.gz
          wget --no-verbose "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${SDK_VERSION}/toolchain_linux-x86_64_arm-zephyr-eabi.tar.gz"
          tar -xf toolchain_linux-x86_64_arm-zephyr-eabi.tar.gz -C zephyr-sdk-${SDK_VERSION}
          pushd zephyr-sdk-${SDK_VERSION}
          SDK_PATH=$PWD
          ./setup.sh -h -c
          readlink -f "$PWD/arm-zephyr-eabi/bin" >> $GITHUB_PATH
          popd
          popd
      
      - name: setup west
        run: |
          echo "Workflow being run by ${{ github.actor }} ID: ${{ github.actor_id }}"
          echo "Github SHA commit ID: ${{ github.sha }}"
          west init -l .
          west update

      - name: build for primary board
        run: |
          pushd ..
          ln -sf zephyr_rv zephyr
          popd
          source ${{ runner.temp }}/../toolchain/zephyr-sdk-${SDK_VERSION}/environment-setup-x86_64-pokysdk-linux
          west build -b qemu_cortex_m3 samples/hello_world -- -G"Unix Makefiles"
